theme: jekyll-theme-minimal
title: Beagy lab utmutato
description: Kando Kalman VIllamosmernoki Kar Beagy lab utmutato

remote_theme: pmarsceill/just-the-docs
color_scheme: dark



# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/X2Cscope/X2Cscope.github.io" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately